name: "Action print input provided"
inputs:
  input-entered:
    description: "The text to print"
    required: true
    default: "Hello world"

runs:
  using: "composite"
  steps:
    - run: echo Printing.... ${{inputs.input-entered}}.
      shell: bash
      name: Echo the provided input
