name: "Action print input provided"
inputs:
  input-entered:
    description: "The text to print"
    required: true
    default: "Hello world"
outputs:
  today-date:
    description: "The date of today"
    value: date

runs:
  using: "composite"
  steps:
    - run: echo Printing.... ${{input.input-entered}}.
      shell: bash
      name: Echo the provided input
    - run: date
      shell: bash
      name: Echo today-date
