name: Custom action output

on:
  push:
  workflow_dispatch:

jobs:
  Action-Output:
    runs-on: ubuntu-latest
    steps:
      - name: custom output
        id: show_output
        run: |
          echo "Hello world"
          echo "::workflow-command parameter1={data},parameter2={data}::{command value}"
        shell: bash
