name: action conditions

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      in_school:
        type: boolean
        description: "is in school"
        required: true
        default: false
    outputs:
      my_output:
        description: "my output"
        required: true
        default: "Done processing"

env:
  is_student: true
  is_teacher: false
  myname: empty

jobs:
  Run-if:
    runs-on: ubuntu-latest
    env: 
      name: Samuel

    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - name: show value
        run: | 
          echo "::error title=Missing semicolon"
        shell: bash
