# name: Say greeting to people
# on: [push]
# jobs:
#   Say-hello:
#     runs-on: ubuntu-latest
#     steps:
#       - shell: bash
#         run: |
#           echo Hello world
#         name: Run hello world
