name: "Simple act"
on:
  push:

jobs:
  LocalAction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Demo
        run: |
          php -v
        shell: bash

      # - uses: ./.github/actions/echoOutput
