name: "Action that send generated output to workflow"
env:
  MyName: "Samuel"
# outputs:
#   today-date:
#     description: "The date of today"
#     value: date

runs:
  using: "composite"
  steps:
    - name: Say my name
      run: |
        echo ${{ env.MyName }}
      shell: bash
      
    # - run: echo "::set-output name=date-id::$(date)"
    #   shell: bash
    #   name: Return today-date
    #   id: date
