name: "Action that send generated output to workflow"
outputs:
  today-date:
    description: "The date of today"
    value: date

runs:
  using: "composite"
  steps:
    - run: echo "::set-output name=date-id::$(date)"
      shell: bash
      name: Return today-date
      id: date
