name: Action print input provided
input:
  input-entered:
    description: "The text to print"
    required: true
    default: "Hello world"
output:
  today-date:
    description: "The date of today"
    value:

runs:
  using: "composite"
  steps:
    - name: Echo the provided input
    - run: echo Printing.... ${{input.input-entered}}.
      shell: bash
    - name: Echo today-date
    - run: date
      shell: bash
