name: Custom action output

on:
  push:
  workflow_dispatch:

jobs:
  Action-Output:
    runs-on: ubuntu-latest
    steps:
      - name: custom output
        id: show_output
        run: |
          echo "HelloWorld" >> $GITHUB_STEP_SUMMARY
        shell: bash
