name: Custom action output

on:
  push:
  workflow_dispatch:

jobs:
  Action-Output:
    runs-on: ubuntu-latest
    steps:
      - name: custom output
        id: show_output
        run: |
          echo "Hello=002" >> $GITHUB_ENV;
          echo ${{ env.Hello }};
        shell: bash

      - name: data value
        run: |
          echo ${{ env.Hello }};
        shell: bash
