name: exec-file
on: [push]
jobs:
  run-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: node index.js
      - env:
          NAME: hello world app
