name: "Delete workflow runs"
on:
  push:

env:
  GITHUB_TOKEN : ${{ secrets.AUTH_GITHUB_TOKEN }}
  LIMIT: 100
  DAYS: 30

jobs:
  FetchWorkflow:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: gh run list --json databaseId,createdAt --limit ${{ env.LIMIT }}> data.json

      - run: |
          jq --arg days ${{ env.DAYS }} '.[] | select((now - (.createdAt | fromdate)) > ($days | tonumber)) | .databaseId' data.json |
          xargs -IID gh api \
            "repos/$(gh repo view --json nameWithOwner -q .nameWithOwner)/actions/runs/ID" \
           -X DELETE
        shell: bash

